version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb+srv://atharva:GpcrJwGmEHlzbF0E@cluster0.5gghydl.mongodb.net/chatbot?retryWrites=true&w=majority&appName=Cluster0
      - JWT=jdchsncsdkfjhjysdhqwe79w3eye8397r3832hfdwe923043yi43oiu439pc
      - COOKIE_SECRET=gbcidasvfwehoh2io3ujhsdvcikuwegf892390eifu29fyhbvckjsdsni
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080/api
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules 